Updates Fireaxe.dm to include multitool method & map changes
spacepunch13/fpstation pull request #83
Opened 2019-05-13 22:53 UTC by borndeadman

i ran mapmerger

[Guidelines]: # (Be sure that your PR follows our guidelines, such as modularization and comment standards. You can read more about the subject here: https://github.com/brushtool/fpstation/blob/master/fpstation/README.md )

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

## About The Pull Request

## Why It's Good For The Game

thank you fuckynuggets for being passive aggressive :^)

2019-05-13 22:55 UTC, funkynuggets commented
no, god no. People use the fire axe because it's easy, if you do this the next easy step is either using the SM as a handy instant open tool, or using water potassium grenades. The fire axe isn't even that good, the chef can make a knife that does the same damage. all you're doing is pushing people to use more extreme methods, such as emitters/handmade pulse guns/grenades/etc etc

2019-05-13 23:41 UTC, borndeadman commented
@funkynuggets alright 300 intergrity on the fireaxe cabinet and 12 seconds to unlock?

2019-05-14 18:29 UTC, funkynuggets commented
> 
> 
> @funkynuggets alright 300 intergrity on the fireaxe cabinet and 12 seconds to unlock?

I don't think you realize it's not the fire axe is the problem. It's only used because it's convienent, people can use all other methods, such as CLF3 fire, wat pot explosion, locker mech, ripley. People don't steal it for no reason, it's literally the keys for the city and is required when there's no cap/hop. Weisyl said it best, moving the caps office would work better.

2019-05-15 11:51 UTC, ghost requested changes
step_x and step_y break the game
use pixel_x and pixel_y

2019-05-15 11:51 UTC, McBawbaggings commented on _maps/map_files/FacepunchStation/facepunchstation.dmm
> +	step_x = 1;
pixel_x

2019-05-15 11:51 UTC, McBawbaggings commented on _maps/map_files/FacepunchStation/facepunchstation.dmm
> +	step_y = -32
pixel_y

2019-05-15 11:51 UTC, McBawbaggings commented on _maps/map_files/FacepunchStation/facepunchstation.dmm
> +	step_x = -31
pixel_x

2019-05-15 13:01 UTC, closed without merging